
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package DeskBackend.Analizadores;

/** CUP generated class containing symbol constants. */
public class ParserResponseSym {
  /* terminals */
  public static final int DOSPUNTOS = 40;
  public static final int MODIFICACIONUSER = 7;
  public static final int ALINEACION = 25;
  public static final int MODIFCOMP = 15;
  public static final int GUIONBAJO = 39;
  public static final int MODIFICACION = 35;
  public static final int ALFANUMERICO = 45;
  public static final int NOMBRE = 37;
  public static final int MODIFICACIONFORM = 12;
  public static final int RESPUESTA = 3;
  public static final int INDICE = 23;
  public static final int FECHA = 32;
  public static final int FIN = 5;
  public static final int USUARIO = 16;
  public static final int INI = 2;
  public static final int RESPUESTAS = 4;
  public static final int TITULO = 36;
  public static final int FORMULARIO = 18;
  public static final int ID = 19;
  public static final int EOF = 0;
  public static final int CAMPO = 20;
  public static final int CLASE = 22;
  public static final int COMILLA = 41;
  public static final int ADDCOMPS = 13;
  public static final int error = 1;
  public static final int MENOR = 44;
  public static final int ANTIGUO = 34;
  public static final int URL = 30;
  public static final int PASSWORD = 31;
  public static final int ADMIRACION = 42;
  public static final int MAYOR = 43;
  public static final int NUEVO = 17;
  public static final int TEMA = 38;
  public static final int CREACIONUSER = 6;
  public static final int REQUERIDO = 26;
  public static final int CREACION = 33;
  public static final int ELICOMP = 14;
  public static final int ELIMINACIONUSER = 8;
  public static final int CREACIONFORM = 10;
  public static final int COLUMNAS = 29;
  public static final int TEXTO = 21;
  public static final int ELIMINACIONFORM = 11;
  public static final int FILAS = 28;
  public static final int VISIBLE = 24;
  public static final int LOGINUSER = 9;
  public static final int OPCIONES = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INI",
  "RESPUESTA",
  "RESPUESTAS",
  "FIN",
  "CREACIONUSER",
  "MODIFICACIONUSER",
  "ELIMINACIONUSER",
  "LOGINUSER",
  "CREACIONFORM",
  "ELIMINACIONFORM",
  "MODIFICACIONFORM",
  "ADDCOMPS",
  "ELICOMP",
  "MODIFCOMP",
  "USUARIO",
  "NUEVO",
  "FORMULARIO",
  "ID",
  "CAMPO",
  "TEXTO",
  "CLASE",
  "INDICE",
  "VISIBLE",
  "ALINEACION",
  "REQUERIDO",
  "OPCIONES",
  "FILAS",
  "COLUMNAS",
  "URL",
  "PASSWORD",
  "FECHA",
  "CREACION",
  "ANTIGUO",
  "MODIFICACION",
  "TITULO",
  "NOMBRE",
  "TEMA",
  "GUIONBAJO",
  "DOSPUNTOS",
  "COMILLA",
  "ADMIRACION",
  "MAYOR",
  "MENOR",
  "ALFANUMERICO"
  };
}

